name: CI

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "CODE_OF_CONDUCT.md"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache npm modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            !~/.npm/_logs
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-

      - name: Install dependecies
        run: npm install

      - name: Run Linter
        run: npm run lint
